=== martindholmes/MICASE/data/micasex.dtd
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Gemma Lum (University of Michigan) -->
<!-- MICASE DTD, based loosely on the TEI, with a local extension for OVERLAP. -->
<!-- xmlified by LB -->
<!ELEMENT TEI.2 (TEIHEADER, TEXT)>
<!ATTLIST TEI.2
	N CDATA #IMPLIED
	ID CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "TEI.2"
>
<!ELEMENT TEICORPUS.2 (TEIHEADER, TEI.2+)>
<!ATTLIST TEICORPUS.2
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "TEICORPUS.2"
>
<!ELEMENT TEIHEADER (FILEDESC, PROFILEDESC)>
<!ATTLIST TEIHEADER
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TYPE CDATA "TEXT"
	CREATOR CDATA #IMPLIED
	STATUS (NEW | UPDATE) "NEW"
	DATE.CREATED CDATA #IMPLIED
	DATE.UPDATED CDATA #IMPLIED
	TEIFORM CDATA "TEIHEADER"
>
<!ELEMENT FILEDESC (TITLESTMT, PUBLICATIONSTMT, SOURCEDESC+)>
<!ATTLIST FILEDESC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "FILEDESC"
>
<!ELEMENT TITLESTMT (TITLE+, (RESPSTMT)*)>
<!ATTLIST TITLESTMT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "TITLESTMT"
>
<!ELEMENT RESPSTMT (RESP | NAME)*>
<!ATTLIST RESPSTMT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "RESPSTMT"
>
<!ELEMENT RESP (#PCDATA)>
<!ATTLIST RESP
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "RESP"
>
<!ELEMENT PUBLICATIONSTMT (P+ | (PUBLISHER | DISTRIBUTOR | AUTHORITY | PUBPLACE | ADDRESS | IDNO | AVAILABILITY | DATE)+)>
<!ATTLIST PUBLICATIONSTMT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "PUBLICATIONSTMT"
>
<!ELEMENT PUBLISHER (#PCDATA)>
<!ATTLIST PUBLISHER
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "PUBLISHER"
>
<!ELEMENT PUBPLACE (#PCDATA)>
<!ATTLIST PUBPLACE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "PUBPLACE"
>
<!ELEMENT DISTRIBUTOR (#PCDATA)>
<!ATTLIST DISTRIBUTOR
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "DISTRIBUTOR"
>
<!ELEMENT AUTHORITY (#PCDATA)>
<!ATTLIST AUTHORITY
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "AUTHORITY"
>
<!ELEMENT IDNO (#PCDATA)>
<!ATTLIST IDNO
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TYPE CDATA #IMPLIED
	TEIFORM CDATA "IDNO"
>
<!ELEMENT AVAILABILITY (P)+>
<!ATTLIST AVAILABILITY
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	STATUS (FREE | UNKNOWN | RESTRICTED) #IMPLIED
	TEIFORM CDATA "AVAILABILITY"
>
<!ELEMENT SOURCEDESC (P | RECORDINGSTMT)+>
<!ATTLIST SOURCEDESC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TEIFORM CDATA "SOURCEDESC"
>
<!ELEMENT RECORDINGSTMT (P+ | RECORDING+)>
<!ATTLIST RECORDINGSTMT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "RECORDINGSTMT"
>
<!ELEMENT RECORDING (P+ | (RESPSTMT | EQUIPMENT | DATE)*)>
<!ATTLIST RECORDING
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TYPE (AUDIO | VIDEO) "AUDIO"
	DUR CDATA #IMPLIED
	TEIFORM CDATA "RECORDING"
>
<!ELEMENT EQUIPMENT (P)+>
<!ATTLIST EQUIPMENT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TEIFORM CDATA "EQUIPMENT"
>
<!ELEMENT PROFILEDESC (CREATION?, LANGUSAGE*, PARTICDESC*, SETTINGDESC*)>
<!ATTLIST PROFILEDESC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "PROFILEDESC"
>
<!ELEMENT CREATION (#PCDATA)>
<!ATTLIST CREATION
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "CREATION"
>
<!ELEMENT LANGUSAGE (P | LANGUAGE)+>
<!ATTLIST LANGUSAGE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TEIFORM CDATA "LANGUSAGE"
>
<!ELEMENT LANGUAGE (#PCDATA)>
<!ATTLIST LANGUAGE
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	ID ID #IMPLIED
	WSD ENTITY #IMPLIED
	USAGE CDATA #IMPLIED
	TEIFORM CDATA "LANGUAGE"
>
<!ELEMENT PARTICDESC (P+ | ((PERSON | PERSONGRP)+, PARTICLINKS?))>
<!ATTLIST PARTICDESC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TEIFORM CDATA "PARTICDESC"
>
<!ELEMENT PERSON ((AFFILIATION | BIRTH | EDUCATION | FIRSTLANG | LANGKNOWN | OCCUPATION | RESIDENCE | SOCECSTATUS)*)>
<!ATTLIST PERSON
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	ROLE CDATA #IMPLIED
	SEX (M | F | U) #IMPLIED
	AGE CDATA #IMPLIED
	RESTRICT (ALL | CITE | NONE) #IMPLIED
	TEIFORM CDATA "PERSON"
>
<!ELEMENT PERSONGRP (AFFILIATION | BIRTH | EDUCATION | FIRSTLANG | LANGKNOWN | OCCUPATION | RESIDENCE | SOCECSTATUS)*>
<!ATTLIST PERSONGRP
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	ROLE CDATA #IMPLIED
	SEX (M | F | U | X) #IMPLIED
	AGE CDATA #IMPLIED
	SIZE CDATA #IMPLIED
	TEIFORM CDATA "PERSONGRP"
>
<!ELEMENT BIRTH (#PCDATA)>
<!ATTLIST BIRTH
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DATE CDATA #IMPLIED
	TEIFORM CDATA "BIRTH"
>
<!ELEMENT FIRSTLANG (#PCDATA)>
<!ATTLIST FIRSTLANG
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "FIRSTLANG"
>
<!ELEMENT LANGKNOWN (#PCDATA)>
<!ATTLIST LANGKNOWN
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "LANGKNOWN"
>
<!ELEMENT RESIDENCE (#PCDATA)>
<!ATTLIST RESIDENCE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "RESIDENCE"
>
<!ELEMENT EDUCATION (#PCDATA)>
<!ATTLIST EDUCATION
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "EDUCATION"
>
<!ELEMENT AFFILIATION (#PCDATA)>
<!ATTLIST AFFILIATION
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "AFFILIATION"
>
<!ELEMENT OCCUPATION (#PCDATA)>
<!ATTLIST OCCUPATION
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	SCHEME IDREF #IMPLIED
	CODE IDREF #IMPLIED
	TEIFORM CDATA "OCCUPATION"
>
<!ELEMENT SOCECSTATUS (#PCDATA)>
<!ATTLIST SOCECSTATUS
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	SCHEME IDREF #IMPLIED
	CODE IDREF #IMPLIED
	TEIFORM CDATA "SOCECSTATUS"
>
<!ELEMENT PARTICLINKS (P+ | RELATION+)>
<!ATTLIST PARTICLINKS
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "PARTICLINKS"
>
<!ELEMENT RELATION EMPTY>
<!ATTLIST RELATION
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TYPE CDATA "PERSONAL"
	DESC CDATA #IMPLIED
	ACTIVE IDREFS #IMPLIED
	PASSIVE IDREFS #IMPLIED
	MUTUAL (Y | N) "Y"
	TEIFORM CDATA "RELATION"
>
<!ELEMENT SETTING (P+ | (NAME | TIME | LOCALE | ACTIVITY)*)>
<!ATTLIST SETTING
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	WHO IDREFS #IMPLIED
	TEIFORM CDATA "SETTING"
>
<!ELEMENT LOCALE (#PCDATA)>
<!ATTLIST LOCALE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "LOCALE"
>
<!ELEMENT ACTIVITY (#PCDATA)>
<!ATTLIST ACTIVITY
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "ACTIVITY"
>
<!ELEMENT SETTINGDESC (P+ | SETTING+)>
<!ATTLIST SETTINGDESC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TEIFORM CDATA "SETTINGDESC"
>
<!ELEMENT DATE (#PCDATA)>
<!ATTLIST DATE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	CALENDAR CDATA #IMPLIED
	VALUE CDATA #IMPLIED
	CERTAINTY CDATA #IMPLIED
	TEIFORM CDATA "DATE"
>
<!ELEMENT TIME (#PCDATA)>
<!ATTLIST TIME
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	VALUE CDATA #IMPLIED
	TYPE (AM | PM | 24HOUR | DESCRIPTIVE) #IMPLIED
	ZONE CDATA #IMPLIED
	TEIFORM CDATA "TIME"
>
<!ELEMENT NAME (#PCDATA)>
<!ATTLIST NAME
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "NAME"
>
<!ELEMENT ADDRESS (#PCDATA)>
<!ATTLIST ADDRESS
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "ADDRESS"
>
<!ELEMENT ABBR (#PCDATA)>
<!ATTLIST ABBR
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	EXPAN CDATA #IMPLIED
	RESP IDREF #IMPLIED
	CERT CDATA #IMPLIED
	TYPE CDATA #IMPLIED
	TEIFORM CDATA "ABBR"
>
<!ELEMENT EXPAN (#PCDATA)>
<!ATTLIST EXPAN
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	ABBR CDATA #IMPLIED
	RESP IDREF #IMPLIED
	CERT CDATA #IMPLIED
	TYPE CDATA #IMPLIED
	TEIFORM CDATA "EXPAN"
>
<!ELEMENT SIC (#PCDATA)>
<!ATTLIST SIC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	CORR CDATA #IMPLIED
	RESP IDREF #IMPLIED
	CERT CDATA #IMPLIED
	TEIFORM CDATA "SIC"
>
<!ELEMENT CORR (#PCDATA)>
<!ATTLIST CORR
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	SIC CDATA #IMPLIED
	RESP CDATA #IMPLIED
	CERT CDATA #IMPLIED
	TEIFORM CDATA "CORR"
>
<!ELEMENT UNCLEAR (#PCDATA)>
<!ATTLIST UNCLEAR
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	REASON CDATA #IMPLIED
	RESP CDATA #IMPLIED
	CERT CDATA #IMPLIED
	HAND IDREF #IMPLIED
	AGENT CDATA #IMPLIED
	TEIFORM CDATA "UNCLEAR"
>
<!ELEMENT SEG (#PCDATA)>
<!ATTLIST SEG
	ANA IDREFS #IMPLIED
	CORRESP IDREFS #IMPLIED
	NEXT IDREF #IMPLIED
	PREV IDREF #IMPLIED
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TYPE CDATA #IMPLIED
	FUNCTION CDATA #IMPLIED
	SUBTYPE CDATA #IMPLIED
	PART (Y | N | I | M | F) "N"
	TEIFORM CDATA "SEG"
>
<!ELEMENT FOREIGN (#PCDATA | SEG)*>
<!ATTLIST FOREIGN
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	LANG IDREF #IMPLIED
	TEIFORM CDATA "FOREIGN"
>
<!ELEMENT OVERLAP (#PCDATA)>
<!ATTLIST OVERLAP
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "OVERLAP"
>
<!ELEMENT U (#PCDATA | ABBR | EXPAN | NAME | CORR | SIC | UNCLEAR | FOREIGN | HI | TITLE | OVERLAP | EVENT | PAUSE | SEG | SHIFT | U | WRITING | GAP)*>
<!ATTLIST U
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	START IDREF #IMPLIED
	END IDREF #IMPLIED
	DUR CDATA #IMPLIED
	TRANS (SMOOTH | LATCHING | OVERLAP | PAUSE) "SMOOTH"
	RESTRICT (ALL | CITE | NONE) #IMPLIED
	WHO IDREF #IMPLIED
	TEIFORM CDATA "U"
>
<!ELEMENT PAUSE EMPTY>
<!ATTLIST PAUSE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	START IDREF #IMPLIED
	END IDREF #IMPLIED
	DUR CDATA #IMPLIED
	TYPE CDATA #IMPLIED
	WHO IDREF #IMPLIED
	TEIFORM CDATA "PAUSE"
>
<!ELEMENT GAP EMPTY>
<!ATTLIST GAP
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DESC CDATA #IMPLIED
	REASON CDATA #IMPLIED
	RESP CDATA #IMPLIED
	AGENT CDATA #IMPLIED
	EXTENT IDREF #IMPLIED
	TEIFORM CDATA "GAP"
>
<!ELEMENT EVENT EMPTY>
<!ATTLIST EVENT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	START IDREF #IMPLIED
	END IDREF #IMPLIED
	DUR CDATA #IMPLIED
	WHO IDREF #IMPLIED
	ITERATED (Y | N | U) "N"
	DESC CDATA #IMPLIED
	TEIFORM CDATA "EVENT"
>
<!ELEMENT WRITING (#PCDATA)>
<!ATTLIST WRITING
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	WHO IDREF #IMPLIED
	TYPE CDATA #IMPLIED
	SCRIPT IDREF #IMPLIED
	GRADUAL (Y | N | U) #IMPLIED
	TEIFORM CDATA "WRITING"
>
<!ELEMENT SHIFT EMPTY>
<!ATTLIST SHIFT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	WHO IDREF #IMPLIED
	FEATURE (TEMPO | LOUD | PITCH | TENSION | RHYTHM | VOICE) #REQUIRED
	NEW CDATA "NORMAL"
	TEIFORM CDATA "SHIFT"
>
<!ELEMENT P (#PCDATA | HI | TITLE | GAP)*>
<!ATTLIST P
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "P"
>
<!ELEMENT HI (#PCDATA)>
<!ATTLIST HI
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "HI"
>
<!ELEMENT TITLE (#PCDATA | HI)*>
<!ATTLIST TITLE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "TITLE"
>
<!ELEMENT TEXT (BODY)>
<!ATTLIST TEXT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "TEXT"
>
<!ELEMENT BODY (P | EVENT | PAUSE | SHIFT | U)+>
<!ATTLIST BODY
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "BODY"
>
<!--

<!ENTITY % ISOgrk1 PUBLIC
       "ISO 8879:1986//ENTITIES Greek Letters//EN">
%ISOgrk1;

<!ENTITY % ISOlat1 PUBLIC "ISO 8879-1986//ENTITIES Added Latin 1//EN">
%ISOlat1; 

<!ENTITY % ISOlat2 PUBLIC "ISO 8879-1986//ENTITIES Added Latin 2//EN">
%ISOlat2; 

<!ENTITY % ISOnum  
  PUBLIC   "ISO 8879-1986//ENTITIES Numeric and Special Graphic//EN">
%ISOnum;

<!ENTITY % ISOpub  PUBLIC "ISO 8879-1986//ENTITIES Publishing//EN">
%ISOpub; 

<!NOTATION cgm PUBLIC
  'ISO 8632:1987//NOTATION Computer Graphics Metafile//EN' >

<!NOTATION cgmchar PUBLIC
  'ISO 8632-2:1987//NOTATION CGM Character Encoding//EN' >

<!NOTATION jpeg PUBLIC
  'ISO DIS 10918//NOTATION JPEG Graphics Format//EN' >

<!NOTATION tiff PUBLIC
  '-//Aldus Corporation//NOTATION Tagged Image File Format//EN' >

<!NOTATION gif PUBLIC
  '-//Compuserve Information Service//NOTATION Graphics Interchange Format//EN' >

<!NOTATION sgml PUBLIC
  'ISO 8879:1986//NOTATION Standard Generalized Markup Language//EN' >

<!NOTATION wsd  PUBLIC
  '-//TEI P3-1994//NOTATION Writing System Declaration//EN' >
-->

=== martindholmes/MICASE/data/lel140su074.xml
<!DOCTYPE TEI.2 SYSTEM "micasex.dtd">
<TEI.2 ID="lel140su074">
  <TEIHEADER>
    <FILEDESC>
      <TITLESTMT>
        <TITLE> Japanese Literature Lecture </TITLE>
        <TITLE> Rackham Div: HA </TITLE>
      </TITLESTMT>
      <WORDCOUNT> 8213 </WORDCOUNT>
      <PUBLICATIONSTMT>
        <PUBLISHER> Michigan Corpus of Academic Spoken English, English Language Institute, University of Michigan </PUBLISHER>
        <IDNO> LEL140SU074 </IDNO>
        <AVAILABILITY>
          <P> The MICASE project is owned by the Regents of the University of Michigan, who hold the copyright.  The database has been developed by the English Language Institute, and the web interface by Digital Library Production Services.  The original DAT audiotapes are held in the English Language Institute and may be consulted by bona fide researchers under special arrangements.  The database is freely available at this website for study, teaching and research purposes, and copies of the transcripts may be distributed, as long as either this statement of availability or the citation given below appears in the text.  However, if any portion of this material is to be used for commercial purposes, such as for textbooks or tests, permission must be obtained in advance and a license fee may be required.  Furthermore, some restrictions apply on the citation of specific portions of some of the transcripts in educational presentations and publications; all such restrictions are noted at the end of this statement.  For further information about copyright permissions, please contact Dr. Sarah Briggs at slbriggs@umich.edu. </P>
          <P> The recommended citation for MICASE is: R. C. Simpson, S. L. Briggs, J. Ovens, and J. M. Swales.  (1999) The Michigan Corpus of Academic Spoken English.  Ann Arbor, MI:  The Regents of the University of Michigan </P>
          <P> RESTRICTIONS ON CITATION OF EXAMPLES:  NONE </P>
        </AVAILABILITY>
      </PUBLICATIONSTMT>
      <SOURCEDESC>
        <RECORDINGSTMT>
          <RECORDING DUR="44">
            <DATE> November 29, 1999 </DATE>
            <EQUIPMENT>
              <P> TASCAM Digital Audio Tape Recorder with two external microphones </P>
            </EQUIPMENT>
            <RESPSTMT>
              <NAME> Bonnie Malczewski </NAME>
              <RESP> Recording </RESP>
              <NAME> Rodney Pratt </NAME>
              <RESP> Transcribing </RESP>
              <NAME> Amy Burke </NAME>
              <RESP> Rechecking </RESP>
              <NAME> Shannon Allen </NAME>
              <RESP> Proofreading </RESP>
              <NAME> Chris Frost </NAME>
              <RESP> Final Editing, 1/25/02 </RESP>
            </RESPSTMT>
          </RECORDING>
        </RECORDINGSTMT>
      </SOURCEDESC>
    </FILEDESC>
    <PROFILEDESC>
      <LANGUSAGE>
        <P> Primary Discourse Mode: MLG </P>
        <P> New Interactivity Rating: MM </P>
        <LANGUAGE ID="NS"> Native Speaker </LANGUAGE>
      </LANGUSAGE>
      <PARTICDESC>
        <PERSONGRP ROLE="Students" SIZE="60"></PERSONGRP>
        <PERSONGRP ROLE="Speakers" SIZE="7"></PERSONGRP>
        <PERSON ID="S1" LANG="NS" ROLE="JF, Instructor" SEX="M" RESTRICT="NONE" AGE="3"></PERSON>
        <PERSON ID="S2" LANG="NS" ROLE="SU, Student" SEX="F" RESTRICT="NONE" AGE="1"></PERSON>
        <PERSON ID="S3" LANG="NS" ROLE="SU, Student" SEX="F" RESTRICT="NONE" AGE="1"></PERSON>
        <PERSON ID="S4" LANG="NS" ROLE="JU, Student" SEX="M" RESTRICT="NONE" AGE="1"></PERSON>
        <PERSON ID="S5" LANG="NS" ROLE="JG, GSI" SEX="F" RESTRICT="NONE" AGE="3"></PERSON>
        <PERSON ID="S6" LANG="NS" ROLE="SU, Student" SEX="M" RESTRICT="NONE" AGE="1"></PERSON>
        <PERSON ID="S7" LANG="NS" ROLE="SU, Student" SEX="M" RESTRICT="NONE" AGE="1"></PERSON>
        <PERSON ID="SS" LANG="NS" ROLE="UN, Unkown" SEX="U" RESTRICT="NONE" AGE="0"></PERSON>
        <PERSON ID="SU-f" LANG="NS" ROLE="SU, Student" SEX="F" RESTRICT="NONE" AGE="1"></PERSON>
        <PERSON ID="SU-m" LANG="NS" ROLE="SU, Student" SEX="M" RESTRICT="NONE" AGE="1"></PERSON>
      </PARTICDESC>
      <SETTINGDESC>
        <SETTING>
          <P> Auditorium, Modern Language Building </P>
        </SETTING>
      </SETTINGDESC>
    </PROFILEDESC>
  </TEIHEADER>
  <TEXT>
    <BODY>
      <U WHO="S1"> okay thankful. something. okay um, we have a list of names 
        <EVENT DESC="BREAK IN RECORDING" />
         act eleven, uh we begin with a list of the, supposedly forty-seven. actually if you read the footnotes, forty-six 
        <FOREIGN> ronin </FOREIGN>
         forty-six samurai supposed to be forty-seven, who carried out the attack, and, we get this whole list of names and they're all equated with the Japanese syllabary, the Japanese Kana. uh there're forty-seven Kana. i guess that's a good way to remember how many Kana there are. um, and the original name the real name of this play this particular version, is, uh oh, where's the chalk? there it is... uh, is, it's in the notes uh, 
        <WRITING> Kanadehon, Chushingura </WRITING>
        <EVENT DUR=":04" DESC="PAUSE WHILE WRITING" />
         uh Kana, remember Kana? is the native Japanese s- uh, syllabary. Kanadehon, and Kanadehon the whole thing is a copybook of Kana. it's a kind of a copybook that people would use for studying Kana. uh and it it's given this name because there are forty-seven 
        <FOREIGN> ronin, </FOREIGN>
         the forty-seven samurai. um and so, it's equivalent to the forty-seven, letters in the syllabary. and so in this beginning of act eleven we get, sort of the list, of all of them, supposedly all of them. the note's kind of interesting it it noted that, the names are in fact different though, they conflict with the names mentioned in act ten. and that was a problem because we had three authors for this particular play and they obviously didn't get all their names, correct with each other. um, okay, in this act, Yuranosuke and his men go to attack Enya Hangan at his castle, and they break in, and they're attacking, and you remember, the samurai of the two neighboring castles and at the at the places nearby hear all the commotion, and they come out to see what's going on. on page one-seventy-five. and they come out and they say 
        <SEG TYPE="READING"> what are all those wild noises coming from your mansion? we hear shouts, swords clashing, the cries of archers. what's going on? is it a drunken brawl? have bandits broken in? or has someone_ has some sudden decree come from the government? our master commands us to find out. narrator. their voices ring loudly. Yuranosuke answers at once. </SEG>
         and remember Yuranosuke is our model of samurai behavior, he's our, ideal samurai here. and he says, in a loud voice h- he doesn't hide from anyone he says, 
        <SEG TYPE="READING"> we are the retainers of Enya Hangan. forty and more of us are fighting with every means at our disposal to avenge our master. i am Oboshi Yuranosuke and this is Hara Goemon, we have no quarrel with Takauji or his brother. nor do we bear any grudge against either Lord Nikki or Lord Ishido. so we promise to do nothing irresponsible. i have ordered our men to take the strictest precautions against fire. so you need have no worries on that account. we only ask, we ask only that you peaceably refrain from interfering. but if you can't turn a deaf ear to what happens in a neighbor's house, and send in reinforcements, we will have no choice but to retaliate with our arrows. </SEG>
         he says we don't have a fight with you. but uh, but if you mess with us if you get in the way we'll kill you too, because, this is, this is what we have to do. and, the narrator says 
        <SEG TYPE="READING"> the men of both houses, hearing this bold proclamation shout back. the samurai say, what superb courage. every man who serves a master should behave as you are doing. call if you have any need of us. withdraw the lanterns. </SEG>
         so they they all applaud and they say hey, great, right on you, kill Moronao there. 
        <EVENT WHO="SS" DESC="LAUGH" />
         uh, at least uh, they're not gonna take sides they_ oh this is a good thing uh, vengeance revenge in this case this is what you oughta be doing and, and they praise them as a result, it's kinda interesting. okay. so, they, they take over the castle, they kill lots of people there but at first they can't find Moronao it turns out that he's hiding, he's run away and, and he's cowering in fear hiding but one of them, the narrator on page one-seventy-six says, 
        <SEG TYPE="READING"> Yazama Jutaro Shigeyuki drags in Moronao all but carrying him in his arms. </SEG>
         he finds him. Jutaro says, 
        <SEG TYPE="READING"> hear me everyone, i found him hiding in the wood shed and took him alive. narrator. the others all rush up, bolstered in spirits like a flower touched with dew. Yuranosuke. nobly done. a tremendous feat. but we mustn't kill him hastily. after all he served for a time as a high officer of the government. the proper decorum must be observed, even when killing him. </SEG>
